import Head from 'next/head'

function HContact () {
    return (
        <Head>
            <title>Contact</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icono.ico" />
        </Head>
    )
}
export default HContact;