import Head from 'next/head'

function Header () {
    return (
        <Head>
            <title>Venus Dev</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icono.ico" />
        </Head>
    )
}
export default Header

    
    
    